# coding: utf-8


NPC_UID_PREFIX = 'npc'
# npc详情配置来源
NPC_SRC_PVP_GAMEARENA = 1
NPC_SRC_PVP_GAMEPATCH = 2
NPC_SRC_SYSTEMFRIEND = 3
NPC_SRC_PVP_GAMEVS = 4

# 物品类型定义
GOODS_TYPE_CARD = 1
GOODS_TYPE_EQUIP = 2
GOODS_TYPE_PATCH = 3
GOODS_TYPE_ITEM = 4
GOODS_TYPE_MONEY = 5
GOODS_TYPE_HONOR = 6
GOODS_TYPE_POINT = 7
GOODS_TYPE_PATCHPLAYER = 8
GOODS_TYPE_TREASURE = 9
#GOODS_TYPE_BOX = 10
GOODS_TYPE_GRADE = 11
GOODS_TYPE_PATCHEQUIP = 18
GOODS_TYPE_GACHA_BOX = 19
GOODS_TYPE_ENERGY = 20
GOODS_TYPE_PATCHITEM = 24
GOODS_TYPE_COIN = 100
GOODS_TYPE_STAMINA = 200
GOODS_TYPE_HAPPY = 300
GOODS_TYPE_LOTTERY = 500
GOODS_TYPE_EXP = 2000
GOODS_TYPE_EXP_PERCENT = 2001
GOODS_TYPE_ACTIVENESS = 1200

# 物品类型到属性的映射
GOODS_TYPE_NAME_MAP = {
    GOODS_TYPE_CARD: 'card',
    GOODS_TYPE_EQUIP: 'equip',
    GOODS_TYPE_PATCH: 'patch',
    GOODS_TYPE_ITEM: 'item',
    GOODS_TYPE_PATCHITEM: 'patchitem',
    GOODS_TYPE_MONEY: 'money',
    GOODS_TYPE_HONOR: 'honor',
    GOODS_TYPE_POINT: 'point',
    GOODS_TYPE_PATCHPLAYER: 'patchplayer',
    GOODS_TYPE_TREASURE: 'treasure',
#    GOODS_TYPE_BOX: 'box',
    GOODS_TYPE_GRADE: 'grade',
    GOODS_TYPE_PATCHEQUIP: 'patchequip',
    GOODS_TYPE_GACHA_BOX: 'gacha_box',
    GOODS_TYPE_ENERGY: 'energy',
    GOODS_TYPE_COIN: 'coin',
    GOODS_TYPE_STAMINA: 'stamina',
    GOODS_TYPE_HAPPY: 'happy',
    GOODS_TYPE_EXP: 'exp',
    GOODS_TYPE_EXP_PERCENT: 'exp_percent',
    GOODS_TYPE_LOTTERY: 'lottery',
    GOODS_TYPE_ACTIVENESS: 'activeness',
}
GOODS_NAME_TYPE_MAP = dict((v,k) for k,v in GOODS_TYPE_NAME_MAP.iteritems())
# 类型为数字的物品类型
GOODS_NAME_INT_KEYS = (
    'money', 'honor', 'point', 'grade', 'coin', 'stamina',
    'exp', 'energy', 'battle', 'exp_percent', 'lottery', 'activeness',
)

# CELEBRATION sort类型
CELEBRATION_SORT_PVE_RANKING = 1
CELEBRATION_SORT_ARENA = 3
CELEBRATION_SORT_PVE_MONEY = 4
CELEBRATION_SORT_GAMEVS_WIN = 11
CELEBRATION_SORT_GAMEVS = 12
CELEBRATION_SORT_GAMEVS_RATING = 13


ACTIVITY_CALC_DELTA_POOLS = {}


